name: Test All Plugins
on:
  push:
  schedule:
    - cron: "43 3 * * *" # Runs every day at 3:43 AM UTC

jobs:
  test:
    name: "${{ matrix.repo.name }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
          - name: thin-edge/tedge-demo-container
            workflow: test.yaml
          - name: thin-edge/tedge-container-bundle
            workflow: test.yaml
          - name: thin-edge/tedge-standalone
            workflow: test.yaml
    steps:
      - name: Run builds
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          repo: ${{ matrix.repo.name }}
          ref: main
          workflow: ${{ matrix.repo.workflow }}
          wait-for-completion: "true"
          sync-status: "true"
          wait-timeout-seconds: 3600
