name: Test All Plugins
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "43 3 * * *" # Runs every day at 3:43 AM UTC

jobs:
  test:
    name: "${{ matrix.repo.ui-name }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
          - name: thin-edge/tedge-demo-container
            ui-name: tedge-demo-container
            workflow: test.yaml
          - name: thin-edge/tedge-container-bundle
            ui-name: tedge-container-bundle
            workflow: test.yaml
          - name: thin-edge/tedge-standalone
            ui-name: tedge-standalone
            workflow: test.yaml
          # - name: thin-edge/tedge-actia-tgur
          #   ui-name: tedge-actia-tgur
          #   workflow: test.yaml
          - name: thin-edge/tedge-rugix-core
            ui-name: tedge-rugix-core
            workflow: bake-image.yaml
            ref: v0.9
          - name: thin-edge/tedge-monit-setup
            ui-name: tedge-monit-setup
            workflow: test.yaml
          # - name: thin-edge/opcua-device-gateway-container
          #   ui-name: opcua-device-gateway-container
          #   workflow: test.yaml
          - name: thin-edge/modbus-plugin
            ui-name: modbus-plugin
            workflow: test.yml
          - name: thin-edge/c8y-command-plugin
            ui-name: c8y-command-plugin
            workflow: test.yaml
          - name: thin-edge/tedge-container-plugin
            ui-name: tedge-container-plugin
            workflow: test.yaml
          - name: thin-edge/tedge-parameter-plugin
            ui-name: tedge-parameter-plugin
            workflow: test.yaml
          - name: thin-edge/tedge-inventory-plugin
            ui-name: tedge-inventory-plugin
            workflow: test.yaml
          - name: thin-edge/tedge-nodered-plugin
            ui-name: tedge-nodered-plugin
            workflow: test.yaml
          - name: thin-edge/tedge-rpm-plugin
            ui-name: tedge-rpm-plugin
            workflow: test.yaml
          - name: thin-edge/tedge-apk-plugin
            ui-name: tedge-apk-plugin
            workflow: test.yaml
    steps:
      - name: Run builds
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          repo: ${{ matrix.repo.name }}
          ref: "${{ matrix.repo.ref || 'main' }}"
          workflow: ${{ matrix.repo.workflow }}
          wait-for-completion: "true"
          sync-status: "true"
          wait-timeout-seconds: 3600
